try to continue job after failure

diff --git a/.github/workflows/runallspecmodules.yml b/.github/workflows/runallspecmodules.yml
--- a/.github/workflows/runallspecmodules.yml
+++ b/.github/workflows/runallspecmodules.yml
@@ -67,9 +67,9 @@ jobs:
                           -var "jamfpro_client_secret=${{ secrets.jamfpro_client_secret }}" \
                           -var "jsc_username=${{ secrets.jsc_username }}" \
                           -var "jsc_password=${{ secrets.jsc_password }}" \
-                          -parallelism=1
-            exit_code=$?  # Capture the exit code
-            # Check if the exit code is 1
+                          -parallelism=1 \
+            || exit_code=$?  # Capture the exit code
+            # Check if the exit code is present
             if [ "$exit_code" -ne 0 ]; then
               echo "Terraform apply failed with exit code 1 for: $line" >> "$fail_log"
               non_zero_exit_code_found="true"  # Set to true if any exit code other than 0 is found
