Exit failure when module fails

diff --git a/.github/workflows/runallspecmodules.yml b/.github/workflows/runallspecmodules.yml
--- a/.github/workflows/runallspecmodules.yml
+++ b/.github/workflows/runallspecmodules.yml
@@ -56,18 +56,23 @@ jobs:
           fail_log="/tmp/terraform_failures.log"
           > "$fail_log"  # Clear the file if it exists
 
+          non_zero_exit_code_found="false"
+
           # Read each line from the output file
           while IFS= read -r line; do
             # Run terraform apply with the line as a -var and capture errors
             echo "Applying: $line"
-            if ! terraform apply -auto-approve -var "$line" -var "jamfpro_instance_url=${{ secrets.jamfpro_instance_url }}" \
+            terraform apply -auto-approve -var "$line" -var "jamfpro_instance_url=${{ secrets.jamfpro_instance_url }}" \
                           -var "jamfpro_client_id=${{ secrets.jamfpro_client_id }}" \
                           -var "jamfpro_client_secret=${{ secrets.jamfpro_client_secret }}" \
                           -var "jsc_username=${{ secrets.jsc_username }}" \
                           -var "jsc_password=${{ secrets.jsc_password }}" \
                           -parallelism=1 \
-                          2>> "$fail_log"; then
-              echo "Failed to apply: $line" >> "$fail_log"
+            exit_code=$?  # Capture the exit code
+            # Check if the exit code is 1
+            if [ "$exit_code" -ne 0 ]; then
+              echo "Terraform apply failed with exit code 1 for: $line" >> "$fail_log"
+              non_zero_exit_code_found="true"  # Set to true if any exit code other than 0 is found
             fi
             terraform destroy -auto-approve -var "$line" -var "jamfpro_instance_url=${{ secrets.jamfpro_instance_url }}" \
                           -var "jamfpro_client_id=${{ secrets.jamfpro_client_id }}" \
@@ -78,7 +83,16 @@ jobs:
                           -refresh=false
           done < /tmp/outputbool.txt
 
+          # Set output variable based on exit code
+          echo "non_zero_exit_code_found=$non_zero_exit_code_found" >> $GITHUB_ENV
+
       # Checks that Terraform Apply ran ok - if it didn't, we exit 1
-      - name: Exit code 1 if Terraform Apply failed
-        if: ${{ steps.terraformapplyanddestroy.outcome != 'success' }}
-        run: exit 1
+      - name: Check for non-zero exit code
+        run: |
+          if [ "${{ env.non_zero_exit_code_found }}" == "true" ]; then
+            echo "Terraform apply encountered failures with a non-zero exit code. Check the log for details."
+            cat terraform_failures.log
+            exit code 1
+          else
+            echo "All applies were successful."
+          fi
